spring:
  application:
    name: support.users
  datasource:
    url: jdbc:postgresql://localhost:5432/gaia-pet
    username: postgres
    password: admin
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true


server:
  port: 8081