spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  application:
    name: support.users
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/gaia-pet
    username: postgres
    password: admin
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,loggers
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8081